TAP_DANCE_ENABLE = no
SPLIT_KEYBOARD = yes
RGBLIGHT_ENABLE = yes
WPM_ENABLE = yes
LTO_ENABLE = yes
OLED_ENABLE = yes
CONSOLE_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
COMMAND_ENABLE = no

EXTRAFLAGS += -flto
